---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "dependencies"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"  # 6:00 UTC
    commit-message:
      prefix: "deps"
    assignees:
      - "mrexox"
