[pre-commit]
parallel = true

[pre-commit.commands.lint]
run = "make lint"
glob = "*.go"
stage_fixed = true

[pre-commit.commands.test]
run = "make test"
glob = "*.go"

[pre-commit.commands.lychee]
glob = "*.md"
exclude = "CHANGELOG\\.md"
run = "lychee --max-concurrency 3 {staged_files}"

[pre-commit.commands.typos]
run = "typos --write-changes {staged_files}"
stage_fixed = true
